const  ActionTypes = {
    GET_TOP_WALLPAPERS: 'GET_TOP_WALLPAPERS',
    GET_LATEST_WALLPAPERS : 'GET_LATEST_WALLPAPERS',
    GET_WALLPAPER_INFO : 'GET_WALLPAPER_INFO',
    CREATE_WALLPAPER: 'CREATE_WALLPAPER',
    CREATE_WALLPAPER_FAILED: 'CREATE_WALLPAPER_FAILED',
    GET_COMMENTS: 'GET_COMMENTS'
};


export default Object.freeze(ActionTypes);